### ISSUE TITLE
Slow around Gorgonops

### ISSUE THREAD

**Issue by Mandino16** [AncientCreaturesDeveliper/Ancient-Creatures#4]
When I try and walk past gorgonops, it slows me down, while pushing me away. Also, gorgonops is very small, around 1 block long and maybe 1/2 a block tall? Something is up with the hitboxes, I think. It also has no knockback. It also cant move, only turn.

**Comment by AncientCreaturesDeveliper** [comment]
Okay, think them not walking. Also, Gorgonops in real life were small, only 2 metres, so I have made them life-sized. and I have fixed knockback. Thanks for bringing this to my attention!
